experiment_name: "cifar10_debug"
epochs: 10
num_timesteps: 1000
batch_size: 256
data_dtype: float32
debug: True
model:
  patch_size: 2
  hidden_dim: 384
  num_attention_heads: 6
  num_dit_blocks: 12
  num_context_classes: 10
  num_timesteps: ${num_timesteps}
  vae_name: "ostris/vae-kl-f8-d16"
  in_channels: 16
  dropout: 0.0
  device: null
trainer:
  num_sampling_steps: 50
  loss_fn: "mse_loss"
  validation_interval: 2
  save_every_n_epochs: 2
  keep_n_checkpoints: 2
  # Check all classes
  validation_context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
noise_scheduler:
  type: "cosine"
  num_timesteps: ${num_timesteps}

  # This avoids Hydra from logging runs
hydra:  
  output_subdir: null  
  run:  
    dir: .